"""
APEX — Database Models
All SQLAlchemy ORM models
"""
from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, String, Float, Integer, Boolean, DateTime,
    ForeignKey, JSON, Text, Enum, Index
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import enum

Base = declarative_base()


# ─────────────────────────────────────────────
# Enums
# ─────────────────────────────────────────────

class TradeDirection(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"

class TradeStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    PENDING = "PENDING"

class SignalAction(str, enum.Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"

class AIMode(str, enum.Enum):
    STRATEGY = "STRATEGY"       # AI uses strategy library
    HYBRID = "HYBRID"           # AI uses strategies as hints
    FREE_WILL = "FREE_WILL"     # AI reasons purely from data

class DebateRole(str, enum.Enum):
    BULL = "BULL"
    BEAR = "BEAR"
    ANALYST = "ANALYST"
    RISK_MANAGER = "RISK_MANAGER"
    HEAD_TRADER = "HEAD_TRADER"

class ImpactLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


# ─────────────────────────────────────────────
# Trade Models
# ─────────────────────────────────────────────

class Trade(Base):
    """A real or paper trade executed via OANDA."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True)
    oanda_trade_id = Column(String(64), unique=True, nullable=True)
    instrument = Column(String(20), nullable=False)
    direction = Column(Enum(TradeDirection), nullable=False)
    status = Column(Enum(TradeStatus), default=TradeStatus.OPEN)

    units = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    stop_loss = Column(Float, nullable=True)
    take_profit = Column(Float, nullable=True)

    pnl = Column(Float, default=0.0)
    pnl_pct = Column(Float, default=0.0)

    # Which AI opened this trade
    ai_model = Column(String(50), nullable=True)
    ai_mode = Column(Enum(AIMode), nullable=True)
    strategy_used = Column(String(100), nullable=True)

    # Links to AI decision
    signal_id = Column(Integer, ForeignKey("ai_signals.id"), nullable=True)
    debate_id = Column(Integer, ForeignKey("debates.id"), nullable=True)

    is_paper = Column(Boolean, default=True)
    opened_at = Column(DateTime, default=datetime.utcnow)
    closed_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    signal = relationship("AISignal", back_populates="trade")
    debate = relationship("Debate", back_populates="trades")

    __table_args__ = (
        Index("ix_trades_instrument", "instrument"),
        Index("ix_trades_ai_model", "ai_model"),
        Index("ix_trades_status", "status"),
    )


# ─────────────────────────────────────────────
# AI Signal Models
# ─────────────────────────────────────────────

class AISignal(Base):
    """A trading signal generated by an AI model."""
    __tablename__ = "ai_signals"

    id = Column(Integer, primary_key=True)
    ai_model = Column(String(50), nullable=False)   # gpt4o, claude, gemini, deepseek, grok, qwen
    instrument = Column(String(20), nullable=False)
    action = Column(Enum(SignalAction), nullable=False)
    ai_mode = Column(Enum(AIMode), nullable=False)

    confidence = Column(Float, nullable=True)       # 0.0 - 1.0
    suggested_entry = Column(Float, nullable=True)
    suggested_sl = Column(Float, nullable=True)
    suggested_tp = Column(Float, nullable=True)
    suggested_units = Column(Float, nullable=True)

    reasoning = Column(Text, nullable=True)         # Chain of Thought
    strategies_considered = Column(JSON, default=list)
    strategy_chosen = Column(String(100), nullable=True)
    market_context = Column(JSON, default=dict)     # snapshot of market data

    # Was this signal acted on?
    executed = Column(Boolean, default=False)
    rejected_reason = Column(String(255), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    trade = relationship("Trade", back_populates="signal")

    __table_args__ = (
        Index("ix_signals_model", "ai_model"),
        Index("ix_signals_instrument", "instrument"),
        Index("ix_signals_created", "created_at"),
    )


# ─────────────────────────────────────────────
# Debate Models
# ─────────────────────────────────────────────

class Debate(Base):
    """A full AI debate round (Bull vs Bear vs Analyst vs Risk Manager)."""
    __tablename__ = "debates"

    id = Column(Integer, primary_key=True)
    instrument = Column(String(20), nullable=False)
    triggered_by = Column(String(50), nullable=True)   # which AI triggered the debate

    # Individual agent arguments
    bull_model = Column(String(50), nullable=True)
    bull_argument = Column(Text, nullable=True)
    bull_confidence = Column(Float, nullable=True)

    bear_model = Column(String(50), nullable=True)
    bear_argument = Column(Text, nullable=True)
    bear_confidence = Column(Float, nullable=True)

    analyst_model = Column(String(50), nullable=True)
    analyst_argument = Column(Text, nullable=True)
    analyst_stance = Column(String(20), nullable=True)  # BUY | SELL | HOLD

    risk_model = Column(String(50), nullable=True)
    risk_argument = Column(Text, nullable=True)
    risk_approved = Column(Boolean, nullable=True)

    # Head Trader final decision
    head_trader_model = Column(String(50), nullable=True)
    final_action = Column(Enum(SignalAction), nullable=True)
    final_reasoning = Column(Text, nullable=True)
    final_confidence = Column(Float, nullable=True)

    # Market snapshot at debate time
    market_snapshot = Column(JSON, default=dict)

    consensus_reached = Column(Boolean, default=False)
    duration_seconds = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    trades = relationship("Trade", back_populates="debate")


# ─────────────────────────────────────────────
# Competition Models
# ─────────────────────────────────────────────

class AICompetitor(Base):
    """Tracks each AI's performance in competition mode."""
    __tablename__ = "ai_competitors"

    id = Column(Integer, primary_key=True)
    ai_model = Column(String(50), unique=True, nullable=False)
    display_name = Column(String(100), nullable=False)

    # Current period stats
    virtual_balance = Column(Float, default=100000.0)
    starting_balance = Column(Float, default=100000.0)
    total_pnl = Column(Float, default=0.0)
    total_pnl_pct = Column(Float, default=0.0)

    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    losing_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)

    max_drawdown = Column(Float, default=0.0)
    sharpe_ratio = Column(Float, nullable=True)
    profit_factor = Column(Float, nullable=True)

    # Free will stats
    times_used_strategy = Column(Integer, default=0)
    times_used_hybrid = Column(Integer, default=0)
    times_used_free_will = Column(Integer, default=0)

    rank = Column(Integer, nullable=True)
    is_active = Column(Boolean, default=True)
    period_start = Column(DateTime, default=datetime.utcnow)
    last_trade_at = Column(DateTime, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# ─────────────────────────────────────────────
# News & Events
# ─────────────────────────────────────────────

class NewsSentiment(Base):
    """Cached news sentiment scores per instrument."""
    __tablename__ = "news_sentiment"

    id = Column(Integer, primary_key=True)
    instrument = Column(String(20), nullable=False)
    headline = Column(String(500), nullable=False)
    source = Column(String(100), nullable=True)
    url = Column(String(500), nullable=True)

    sentiment_score = Column(Float, nullable=True)  # -1.0 to 1.0
    sentiment_label = Column(String(20), nullable=True)  # positive|negative|neutral
    model_used = Column(String(50), nullable=True)

    published_at = Column(DateTime, nullable=True)
    fetched_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_news_instrument", "instrument"),
        Index("ix_news_fetched", "fetched_at"),
    )


class EconomicEvent(Base):
    """Economic calendar events."""
    __tablename__ = "economic_events"

    id = Column(Integer, primary_key=True)
    title = Column(String(255), nullable=False)
    currency = Column(String(10), nullable=False)
    impact = Column(Enum(ImpactLevel), nullable=False)

    event_time = Column(DateTime, nullable=False)
    forecast = Column(String(50), nullable=True)
    previous = Column(String(50), nullable=True)
    actual = Column(String(50), nullable=True)

    trading_paused = Column(Boolean, default=False)  # did we pause for this?
    fetched_at = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_events_time", "event_time"),
        Index("ix_events_currency", "currency"),
    )


# ─────────────────────────────────────────────
# Backtest Models
# ─────────────────────────────────────────────

class BacktestRun(Base):
    """A completed backtest run."""
    __tablename__ = "backtest_runs"

    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)
    instrument = Column(String(20), nullable=False)
    granularity = Column(String(10), nullable=False)
    strategy = Column(String(100), nullable=True)
    ai_model = Column(String(50), nullable=True)

    start_date = Column(DateTime, nullable=False)
    end_date = Column(DateTime, nullable=False)
    initial_balance = Column(Float, default=10000.0)

    # Results
    final_balance = Column(Float, nullable=True)
    total_return_pct = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=True)
    win_rate = Column(Float, nullable=True)
    max_drawdown = Column(Float, nullable=True)
    sharpe_ratio = Column(Float, nullable=True)
    profit_factor = Column(Float, nullable=True)
    sortino_ratio = Column(Float, nullable=True)

    parameters = Column(JSON, default=dict)
    equity_curve = Column(JSON, default=list)   # list of {timestamp, equity}
    trade_log = Column(JSON, default=list)

    status = Column(String(20), default="running")  # running | completed | failed
    error_message = Column(Text, nullable=True)
    duration_seconds = Column(Float, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
